name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:
    
permissions:
  contents: read
      
jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -input=false \
          -backend-config="storage_account_name=${{ secrets.TERRAFORM_STORAGE_ACCOUNT_NAME }}" \
          -backend-config="container_name=${{ secrets.TERRAFORM_CONTAINER_NAME }}" \
          -backend-config="key=prod.terraform.tfstate" \
          -backend-config="sas_token=${{ secrets.TERRAFORM_STATE_STORAGE_SAS_TOKEN }}"
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out plan.tfplan -input=false
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve -input=false
